modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/gizmo-ds/smsn-mod/issues"
license = "MIT"

[[mods]]
modId = "smsn"
version = "${version}"
displayName = "Save My Shit Network"
authors = "Gizmo"
description = '''
Block common mods from connecting to the internet without affecting the mods' functionality, preventing slow loading or game crashes caused by network issues.
'''
logoFile = "smsn_logo.png"
displayURL = "https://github.com/gizmo-ds/smsn-mod"

[[dependencies.smsn]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smsn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smsn]]
modId = "cloth_config"
mandatory = false
versionRange = "[11.,)"
ordering = "NONE"
side = "CLIENT"
