[plugins]
architectury = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }
loom = { id = "dev.architectury.loom", version = "1.11-SNAPSHOT" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
dotenv = { id = "co.uzzu.dotenv.gradle", version = "4.0.0" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version = "2.1.6" }

[versions]
lombok = "1.18.38"
mixinextras = "0.4.1"
# Dependencies
parchment = "2023.09.03"
fabric-loader = "0.16.14"
forge = "1.20.1-47.2.32"
clothconfig = "11.1.136"
# Dev
modmenu = "7.2.2"
fabric-api = "0.92.2+1.20.1"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mixinextras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
mixinextras-fabric = { module = "io.github.llamalad7:mixinextras-fabric", version.ref = "mixinextras" }
mixinextras-forge = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinextras" }
# Dependencies
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
forge-forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
clothconfig-api = { module = "me.shedaniel.cloth:cloth-config", version.ref = "clothconfig" }
clothconfig-fabric = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "clothconfig" }
clothconfig-forge = { module = "me.shedaniel.cloth:cloth-config-forge", version.ref = "clothconfig" }
# Dev
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
norealmsbutton-fabric = { version = "pHRo8eLv", module = "maven.modrinth:no-realms-button" } # 2.0.2
norealmsbutton-forge = { version = "TYRKC9pB", module = "maven.modrinth:no-realms-button" } # 2.0.2
forge-moonlight = { version = "1.20-2.14.4-forge", module = "maven.modrinth:moonlight" }
fabric-sodium = { version = "mc1.20-0.4.10", module = "maven.modrinth:sodium" }
forge-patchouli = { version = "1.20.1-83-FORGE", module = "vazkii.patchouli:Patchouli" }
forge-curios = { version = "5.14.1+1.20.1", module = "top.theillusivec4.curios:curios-forge" }
forge-caelus = { version = "3.2.0+1.20.1", module = "top.theillusivec4.caelus:caelus-forge" }
# Fabric
fabric-modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
fabric-xaeros-minimap = { version = "24.2.0_Fabric_1.20", module = "maven.modrinth:xaeros-minimap" }
fabric-xaeros-worldmap = { version = "1.38.8_Fabric_1.20", module = "maven.modrinth:xaeros-world-map" }
fabric-supplementaries = { version = "SFY0zXug", module = "maven.modrinth:supplementaries" } # 1.20-3.1.10
fabric-ipn = { version = "fabric-1.20.1-1.10.11", module = "maven.modrinth:inventory-profiles-next" }
fabric-botania = { version = "1.20.1-446-FABRIC", module = "vazkii.botania:Botania" }
fabric-iris = { version = "URWeWMAt", module = "maven.modrinth:iris" } # 1.6.4+1.20
fabric-mru = { version = "1.0.0+1.20.1-fabric", module = "maven.modrinth:mru" }
fabric-ribbits = { version = "15vB3aE9", module = "maven.modrinth:ribbits" } # 3.0.2
fabric-exposure = { version = "O4Fow0Po", module = "maven.modrinth:exposure" } # 1.7.15
fabric-adastra = { version = "MxqFxL9C", module = "maven.modrinth:ad-astra" } # 1.15.18
fabric-nitrogen = { version = "1.20.1-1.0.15-fabric", module = "com.aetherteam.nitrogen:nitrogen_internals" }
fabric-tenshilib = { version = "5240454", module = "curse.maven:tenshilib-fabric-552662" } # 1.7.6
fabric-createtramadditions = { version = "Szc6mYko", module = "maven.modrinth:create-tram-additions" } # 1.6
fabric-immersiveportals = { version = "v3.3.7-mc1.20.1", module = "com.github.iPortalTeam.ImmersivePortalsMod:imm_ptl_core" }
fabric-majrusz-library = { version = "nfkUUMHq", module = "maven.modrinth:majrusz-library" } # 7.0.8
fabric-kiwi = { version = "11.8.29+fabric", module = "maven.modrinth:kiwi" }
# Forge
forge-xaeros-minimap = { version = "24.2.0_Forge_1.20", module = "maven.modrinth:xaeros-minimap" }
forge-xaeros-worldmap = { version = "1.38.8_Forge_1.20", module = "maven.modrinth:xaeros-world-map" }
forge-supplementaries = { version = "HcdcLvdS", module = "maven.modrinth:supplementaries" } # 1.20-3.1.10
forge-quark = { version = "4.0-462.3531", module = "org.violetmoon.quark:Quark" }
forge-zeta = { version = "1.0-31.143", module = "org.violetmoon.zeta:Zeta" }
forge-botania = { version = "1.20.1-446-FORGE", module = "vazkii.botania:Botania" }
forge-citadel = { version = "2.5.4", module = "maven.modrinth:citadel" }
forge-alexscaves = { version = "1.1.4", module = "maven.modrinth:alexs-caves" }
forge-blueprint = { version = "1.20.1-7.1.0", module = "com.teamabnormals:blueprint" }
forge-obscureapi = { version = "FizVdYUp", module = "maven.modrinth:obscure-api" } # 15
forge-ipn = { version = "forge-1.20.1-1.10.11", module = "maven.modrinth:inventory-profiles-next" }
forge-mru = { version = "1.0.0+1.20.1-forge", module = "maven.modrinth:mru" }
forge-ribbits = { version = "FEcTRv8b", module = "maven.modrinth:ribbits" } # 3.0.2
forge-exposure = { version = "GxlCCDbA", module = "maven.modrinth:exposure" } # 1.7.15
forge-adastra = { version = "WUGYX9Me", module = "maven.modrinth:ad-astra" } # 1.15.18
forge-titanium = { version = "1.20.1-3.8.23", module = "maven.modrinth:titanium" }
forge-immersivecaves = { version = "1.4.1", module = "maven.modrinth:immersive-caves" }
forge-placebo = { version = "1.20.1-8.6.0", module = "dev.shadowsoffire:Placebo" }
forge-enigmaticlegacy = { version = "mkqkIwez", module = "maven.modrinth:enigmatic-legacy" } # 2.29.0
forge-immersiveengineering = { version = "1.20.1-10.0.0-169.48", module = "blusunrize.immersiveengineering:ImmersiveEngineering" }
forge-nitrogen = { version = "1.20.1-1.0.11-neoforge", module = "com.aetherteam.nitrogen:nitrogen_internals" }
forge-baguslib = { version = "VU7aEpro", module = "maven.modrinth:bagus-lib" } # 1.20.1-5.3.0
forge-petrolpark = { version = "fBVOTUaX", module = "maven.modrinth:petrolpark" } # 1.20.1-1.0.6
forge-projecte = { version = "4901949", module = "curse.maven:projecte-226410" } # 1.0.1
forge-hexerei = { version = "hR4PQb6h", module = "maven.modrinth:hexerei" } # 0.4.2.1
forge-voidscape = { version = "5020417", module = "curse.maven:voidscape-251730" } # 1.5.348
forge-tenshilib = { version = "4819252", module = "curse.maven:tenshilib-312040" } # 1.7.2
forge-additionalstructures = { version = "OqEwjVmd", module = "maven.modrinth:additional-structures" } # 4.1.2
forge-createtramadditions = { version = "CBLu5Isq", module = "maven.modrinth:create-tram-additions" } # 1.6
forge-arsnouveau = { version = "qtW93rN7", module = "maven.modrinth:ars-nouveau" } # 4.9.0
forge-immersiveportals = { version = "6368524", module = "curse.maven:immersive-portals-for-forge-355440" } # 3.0.7
forge-majrusz-library = { version = "BZzTRseC", module = "maven.modrinth:majrusz-library" } # 7.0.8
forge-kiwi = { version = "11.8.29+forge", module = "maven.modrinth:kiwi" }
